# MOdel Testing

In [5]:
import pickle
import  json
import numpy as np
import pandas as pd


In [7]:
with open('linear_reg_model.pkl','rb') as f:
    linear_model = pickle.load(f)


linear_model

FileNotFoundError: [Errno 2] No such file or directory: 'linear_reg_model.pkl'

In [7]:
with open("column_data.json",'rb') as f:
    column_data  = json.load(f)

column_data

{'gender': {'male': 1, 'female': 0}, 'smoker': {'yes': 1, 'no': 0}}

In [9]:
column_names = linear_model.feature_names_in_
column_names

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [13]:
len(column_names)

9

In [109]:
fetaure_count = linear_model.n_features_in_
fetaure_count

9

# USER

In [85]:
age = 35
gender = 'male'
bmi = 26.9
children  = 0
smoker = 'no'
region = 'northeast'

In [87]:
gender = column_data['gender'][gender] # 1
gender


1

In [89]:
smoker = column_data['smoker'][smoker] # 0
smoker

0

In [91]:
region = 'region_' + region 
region

'region_northeast'

In [93]:
column_names

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [105]:
np.where(column_names == region)

(array([5], dtype=int64),)

In [95]:
region_index = np.where(column_names == region)[0][0]
region_index

5

In [97]:
test_array = np.zeros(fetaure_count)
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
test_array[0] = age
test_array[1] = gender
test_array[2] = bmi
test_array[3] = children
test_array[4] = smoker
test_array[region_index] = 1


In [101]:
test_array

array([35. ,  1. , 26.9,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ])

In [103]:
predicted_Charges = linear_model.predict([test_array])[0]
print("Predicted Medical Insurance Charges are: ",predicted_Charges)

Predicted Medical Insurance Charges are:  6086.9926644568


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [111]:
def get_predicted_charges(age,gender,bmi,children,smoker,region):
    gender = column_data['gender'][gender]
    smoker = column_data['smoker'][smoker]
    region = 'region_' + region 
    region_index = np.where(column_names == region)[0][0]
    test_array = np.zeros(fetaure_count)

    test_array[0] = age
    test_array[1] = gender
    test_array[2] = bmi
    test_array[3] = children
    test_array[4] = smoker
    test_array[region_index] = 1

    predicted_Charges = linear_model.predict([test_array])[0]

    return f"Predicted Medical Insurance Charges are:{predicted_Charges}"
    

In [113]:
age = 20
gender = 'male'
bmi = 26
children  = 4
smoker = 'yes'
region = 'northwest'

get_predicted_charges(age,gender,bmi,children,smoker,region)


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


'Predicted Medical Insurance Charges are:27765.215236775748'

In [115]:
age = 20
gender = 'female'
bmi = 26
children  = 4
smoker = 'no'
region = 'southwest'

get_predicted_charges(age,gender,bmi,children,smoker,region)

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


'Predicted Medical Insurance Charges are:3264.109829592264'

In [3]:
column_list = ['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest']

column_list.index('age')

0