# Model Testing

In [1]:
import pickle
import  json
import numpy as np
import pandas as pd

In [3]:
with open('linear_reg_model.pkl','rb') as f:
    linear_model = pickle.load(f)


linear_model

C:\Users\GLOBAL\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LinearRegression from version 1.4.2 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


LinearRegression()

In [5]:
with open("column_data.json",'rb') as f:
    column_data  = json.load(f)

column_data

{'gender': {'male': 1, 'female': 0}, 'smoker': {'yes': 1, 'no': 0}}

In [6]:
column_names = linear_model.feature_names_in_
column_names

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [7]:
len(column_names)

9

In [8]:
fetaure_count = linear_model.n_features_in_
fetaure_count

9

# USER

In [9]:
age = 35
gender = 'male'
bmi = 26.9
children  = 0
smoker = 'no'
region = 'northeast'

In [10]:
gender = column_data['gender'][gender] # 1
gender

1

In [11]:
smoker = column_data['smoker'][smoker] # 0
smoker

0

In [12]:
region = 'region_' + region 
region

'region_northeast'

In [13]:

column_names

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [14]:
np.where(column_names == region)

(array([5]),)

In [16]:
region_index = np.where(column_names == region)[0][0]
region_index

np.int64(5)

In [17]:
test_array = np.zeros(fetaure_count)
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
test_array[0] = age
test_array[1] = gender
test_array[2] = bmi
test_array[3] = children
test_array[4] = smoker
test_array[region_index] = 1

In [19]:
test_array

array([35. ,  1. , 26.9,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ])

In [20]:
predicted_Charges = linear_model.predict([test_array])[0]
print("Predicted Medical Insurance Charges are: ",predicted_Charges)

Predicted Medical Insurance Charges are:  6086.992664456804


C:\Users\GLOBAL\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [21]:

def get_predicted_charges(age,gender,bmi,children,smoker,region):
    gender = column_data['gender'][gender]
    smoker = column_data['smoker'][smoker]
    region = 'region_' + region 
    region_index = np.where(column_names == region)[0][0]
    test_array = np.zeros(fetaure_count)

    test_array[0] = age
    test_array[1] = gender
    test_array[2] = bmi
    test_array[3] = children
    test_array[4] = smoker
    test_array[region_index] = 1

    predicted_Charges = linear_model.predict([test_array])[0]

    return f"Predicted Medical Insurance Charges are:{predicted_Charges}"

In [22]:
age = 20
gender = 'male'
bmi = 26
children  = 4
smoker = 'yes'
region = 'northwest'

get_predicted_charges(age,gender,bmi,children,smoker,region)

C:\Users\GLOBAL\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


'Predicted Medical Insurance Charges are:27765.21523677574'

In [24]:

age = 20
gender = 'female'
bmi = 26
children  = 4
smoker = 'no'
region = 'southwest'

get_predicted_charges(age,gender,bmi,children,smoker,region)

C:\Users\GLOBAL\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


'Predicted Medical Insurance Charges are:3264.109829592264'

In [26]:
column_list = ['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest']

column_list.index('age')

0